# Generated by Django 4.2.17 on 2024-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_customuser_is_blocked_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1cd768', max_length=6),
        ),
    ]
