# Generated by Django 4.2.17 on 2025-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0058_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='27cc70', max_length=6),
        ),
    ]
