# Generated by Django 4.2.17 on 2025-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity_per_user',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
