# Generated by Django 4.2.17 on 2025-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productvariant_color_alter_productvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_images',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
