# Generated by Django 4.2.17 on 2025-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_category_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='size',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
