# Generated by Django 4.2.17 on 2025-03-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_color_is_blocked_size_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variants',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
