# Generated by Django 4.2.17 on 2025-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('debited', 'Debited'), ('referral', 'Referral'), ('credited', 'Credited')], max_length=20),
        ),
    ]
